import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


export const metadata = {
  title: "Do an giua ki",
  description: "Generated by create next app",
};

import TopBar from './components/TopBar'
import Categories from './components/Categories'
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className='bg-gray-600 py-12'>
          <div className='w-4/5 mx-auto'>
            <TopBar></TopBar>
            <Categories></Categories>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
