import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/app/contexts/CartProvider";

export const metadata = {
  title: "Do an giua ki",
  description: "Generated by create next app",
};

import TopBar from './components/TopBar';
import Footer from './components/Footer';
import Categories from './components/Categories';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <CartProvider>
          {/* Header Section */}
          <div className='bg-black text-white py-12'>
            <div className='w-4/5 mx-auto'>
              <TopBar />
              <Categories />
            </div>
          </div>

          {/* Main Content */}
          <main className="flex-grow">{children}</main>

          {/* Footer Always at Bottom */}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
